### ISSUE TITLE
No access to ssh via router

### ISSUE THREAD

**Issue by apajon** [introlab/MOvITPlus#10]
I no longer have access to ssh (or VNC) connection using my internet box.

With the wifi access point, everityhing is working well.

**Comment by doumdi** [comment]
@apajon I am able to ssh to all interfaces (wlan0, wlan1, eth0). Can you give me more details about your problems?

**Comment by apajon** [comment]
when the raspberry is connected to my internet box at home and my computer/smartphone too.

Currently I cannot access the ssh connection and got this message
```bash
adrienpajon@MacBook-Air-de-Adrien:~$ ssh pi@192.168.2.36
ssh: connect to host 192.168.2.36 port 22: Host is down
```

Same with VNC, I am unable to reach the host,
```route vers l'hôte inconnue```

However, via the raspberry access point, I have no problem (IP adresse : 192.168.10.1)

**Comment by doumdi** [comment]
Could you print the result of the command ```ifconfig```  and ```iwconfig``` on your raspberry pi?

**Comment by apajon** [comment]
<img width="613" alt="Capture d’écran, le 2021-02-09 à 16 14 12" src="https://user-images.githubusercontent.com/7260230/107429691-30e6e400-6af2-11eb-87ce-75b8c12cd392.png">

<img width="639" alt="Capture d’écran, le 2021-02-09 à 16 14 34" src="https://user-images.githubusercontent.com/7260230/107429705-35130180-6af2-11eb-97a5-4c1694b1bc1c.png">

**Comment by apajon** [comment]
the ip address has changed this morning but I still have the issue

**Comment by doumdi** [comment]
@apajon, From what I understand, you cannot ssh to 192.168.2.38 from your Mac? Can you give me the output of the command on your Mac? I suspect that you have to clean your .ssh/known_hosts to remove the line starting with 192.168.2.38 since the ssh configuration on the pi changed (key).

**Comment by apajon** [comment]
<img width="562" alt="Capture d’écran, le 2021-02-10 à 10 13 45" src="https://user-images.githubusercontent.com/7260230/107529580-03994500-6b89-11eb-970a-87a2b54fde39.png">

**Comment by doumdi** [comment]
@apajon try ping 192.168.2.38 via your Internet box.

**Comment by apajon** [comment]
it worked ... after killing the frontend service. (that's all I have done on the rapsberry)
But I had this problem before the last update and the fail of the frontend service.
I tell you if it appends again after rebooting and restart the frontend service.

<img width="571" alt="Capture d’écran, le 2021-02-10 à 10 32 15" src="https://user-images.githubusercontent.com/7260230/107531904-4e1bc100-6b8b-11eb-8147-34e4761ade35.png">
