### ISSUE TITLE
Connection to web interface instable via wifi (not access point)

### ISSUE THREAD

**Issue by apajon** [introlab/MOvITPlus#11]

**Comment by doumdi** [comment]
@apajon, Add the following to the file /etc/network/interfaces
```bash
auto wlan0
iface wlan0 inet static
address 192.168.10.1
netmask 255.255.255.0

allow-hotplug eth0
iface eth0 inet dhcp

allow-hotplug wlan1
iface wlan1 inet dhcp
    wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf
```

And make sure /etc/wpa_supplicant/wpa_supplicant.conf is configured with something like this :

```bash
country=CA
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1

network={
    ssid="NETWORK_SSID" 
    psk="PASSWORD"
    id_str="AP1"
}

```

**Comment by doumdi** [comment]
@apajon, can you define "instable"? If you want to use the web interface on this interface (wlan1), you must recompile the frontend and set the backend to the same IP address as the IP you get on wlan1. The web interface is meant to work when connected on the local access point with address 192.168.10.1. Have a look at this file : https://github.com/introlab/MOvIT-Detect-Frontend/blob/de64b0bd3bd4103d0839312ca3e707e45749963f/package.json (modify the IP addresses to fit your needs) and follow the install procedure : https://github.com/introlab/MOvIT-Detect-Frontend/tree/de64b0bd3bd4103d0839312ca3e707e45749963f#1-guide-dinstallation

**Comment by apajon** [comment]
By instable I mean, I can go to movitplus web interface.
But, when the raspberry is connected to my internet box at home and my computer/smartphone too, sometimes, I can connect as any users and sometimes, it is stuck at the user choice page saying after waiting a long time "bad password".

Via the raspberry access point, I have no problem to access the webinterface.

**Comment by apajon** [comment]
I am sure that the raspberry is connected to my home network.
It is detected by my box and I have access to internet via the raspberry access point.

**Comment by doumdi** [comment]
@apajon, I  think I have fixed the problem and the web page should now work on any network interface. You will need to update the frontend with those commands : 
```bash
# Go to the frontend directory
cd MOvITPlus/MOvIT-Detect-Frontend
# Pull the latest code
git pull origin master
# Setup yarn and packages
yarn install
# Rebuild the frontend
yarn build
# Reboot 
sudo reboot
```

**Comment by apajon** [comment]
I tried solution and it does not work.
The web interface does not even launch when reboot.

<img width="639" alt="Capture d’écran, le 2021-02-09 à 16 25 45" src="https://user-images.githubusercontent.com/7260230/107430692-81127600-6af3-11eb-9ab9-87ca4af0dde8.png">

**Comment by doumdi** [comment]
@apajon, Could you go to MOvITPlus/MOvIT-Detect-Frontend and do: 
```bash
# Kill service (just in case)
sudo systemctl kill movit_frontend.service
# Update code (just in case)
git pull origin master
# Clean up modules
rm -rf node_modules
# Re-install everything
yarn install
# Re-build package
yarn build
# Start (updated)
sudo yarn start
```
Make sure your Pi have access to the Internet. Could you paste the result of the yarn start command here please?

**Comment by apajon** [comment]
<img width="934" alt="Capture d’écran, le 2021-02-10 à 10 22 01" src="https://user-images.githubusercontent.com/7260230/107531023-6fc87880-6b8a-11eb-9c8b-add67cb60b68.png">
<img width="942" alt="Capture d’écran, le 2021-02-10 à 10 24 51" src="https://user-images.githubusercontent.com/7260230/107531031-71923c00-6b8a-11eb-94ce-a4af45c3bb25.png">
<img width="822" alt="Capture d’écran, le 2021-02-10 à 10 25 23" src="https://user-images.githubusercontent.com/7260230/107531049-7525c300-6b8a-11eb-9f85-fe8e4ed14638.png">
<img width="961" alt="Capture d’écran, le 2021-02-10 à 10 25 40" src="https://user-images.githubusercontent.com/7260230/107531065-78b94a00-6b8a-11eb-8dcc-5cd76d6e2813.png">
<img width="679" alt="Capture d’écran, le 2021-02-10 à 10 25 59" src="https://user-images.githubusercontent.com/7260230/107531085-7c4cd100-6b8a-11eb-9e47-89d3a5172f03.png">

**Comment by doumdi** [comment]
@apajon, Compilation is working fine. The server must be started with :
```bash
sudo yarn start
```

For some reason port 80 is not available to user 'pi'. Could you restart your pi and type the following command :
```bash
sudo systemctl status movit_frontend.service
```

The web interface should then be available from wifi1 interface.

**Comment by apajon** [comment]
It seems to work fine.

I close this issue for the moment

**Comment by apajon** [comment]
It seems to work well for the moment.

I close this issue.
