### ISSUE TITLE
Problem of motion unit after deconnection which implie the freezing of angleanalysis (and maybe other python servicesservices)

### ISSUE THREAD

**Issue by apajon** [introlab/MOvITPlus#12]
<img width="910" alt="Capture d’écran, le 2021-02-05 à 15 41 36" src="https://user-images.githubusercontent.com/7260230/107087398-5f4e8180-67c9-11eb-9221-ad7ff137597a.png">

**Comment by apajon** [comment]
This problem does not occur when connecting/deconnecting the pressure mat and/or the notification module

**Comment by apajon** [comment]
The freezing of AngleAnalysis does not occur everytime.

**Comment by doumdi** [comment]
@apajon, this is really a strange behavior. From what I can understand, the motion sensor "jams" the i2c bus when not working properly. IMUSeatAngle is waiting for the bus, but  never available We will have to investigate. The motion sensor is SPI but is coupled with a I2C range finder (that we do not use at the moment). It may be affected when we reset.

**Comment by doumdi** [comment]
@apajon, I suggest you unplug the module if you want to do tests (will always be in state not moving). This is better than having an no angle at all.
