### ISSUE TITLE
Snooze button does nothing

### ISSUE THREAD

**Issue by apajon** [introlab/MOvITPlus#14]
We set a bascule recommandation as: every 3min, during 1min, at 22°
The notification works well by vibrating and blinking

We choose to set the snooze option at 1min to test it.
But when arrive the time of a notification, and when the module begin to vibrate and blink, nothing happen when we press the snooze button.
The module still vibrate and blink.

However, in the debug, the snooze button is seen to be pressed. "Alarm/isButtonOn" switch from 0 to 1 when pressed and from 1 to 0 when released.

I suspect that nothing is done with this "variable"

**Comment by doumdi** [comment]
@apajon, The button must be pressed for at least 4 seconds to avoid quick pressing the button. This is hard coded in :

https://github.com/introlab/MOvIT-Detect/blob/1f164276c564e50963cfd8de741450e243a7e4c0/python/fsm/NotificationFSM.py#L363 and can be easily changed.

**Comment by apajon** [comment]
We tested it last week and nothing happen when pushing the snooze button.
Even when pressing for a long time >> 4s, maybe 30s.

**Comment by apajon** [comment]
Finally seems to work.

NEED to test on the wheelchair

**Comment by apajon** [comment]
On a testé et finalement ça fonctionne bien.
