### ISSUE TITLE
Ajouter dans les paramètres de l'usager la situation des capteurs

### ISSUE THREAD

**Issue by Marie-LaurenceB** [introlab/MOvITPlus#21]
Ajouter dans les paramètres de l'usager la situation des capteurs. Section 9.2 cahier charge.

Important que l'usager soit au courant si un capteur est mal branché. 

![image](https://user-images.githubusercontent.com/77858297/110138867-6bb20400-7da0-11eb-8eda-1e4ea2a55d95.png)

**Comment by apajon** [comment]
@Marie-LaurenceB
L'image est trop petite, on ne voit rien, tu peux la renvoyer ?
