### ISSUE TITLE
Topo sur l'interace recommandation 

### ISSUE THREAD

**Issue by Marie-LaurenceB** [introlab/MOvITPlus#26]
Erreur   de français : Basculez à tous les X minutes-> Basculez à toutes les X   minutes. Section 7.1 cahier de charge.
--

![erreur topo recommandation usager](https://user-images.githubusercontent.com/77858297/109865677-561ecc00-7c32-11eb-97ef-970a615ae375.JPG)

**Comment by apajon** [comment]
Il y a en effet une faute d'accord suivant ce que l'on veut dire:
- toutes les **X** minutes ou **X** heures
- tous les **X** jours
Le cahier des charges stipulant de prendre le premier accord

Par contre, j'avoue que la formule **à toutes les** avec un **à** est typiquement une formulation canadienne. Ça me fait bizarre à chaque fois. => demander à Claudine s'il faut utiliser l'usage ** canadianisme** ou **français**

[chaque (à chaque)](https://www.btb.termiumplus.gc.ca/tpv2guides/guides/clefsfp/index-fra.html?lang=fra&lettr=indx_catlog_c&page=9YfpINHOAwTo.html)

[tous les… (à)](https://www.btb.termiumplus.gc.ca/tpv2guides/guides/clefsfp/index-fra.html?lang=fra&lettr=indx_catlog_t&page=9KnTrHrbgSp0.html#zz9KnTrHrbgSp0)
C'est pas moi qui le dis c'est le BtB (bureau de la traduction) ;-)
