### ISSUE TITLE
Objectifs personnels ne s'actualise pas 

### ISSUE THREAD

**Issue by Marie-LaurenceB** [introlab/MOvITPlus#28]
Lorsqu'on   change les objectifs personnel et qu'on actualise la page ou qu'on change de   profil pour clinicien, les paramètres sont automatiquement remis à ceux du   clinicien. Les paramètres usagers ne s'enregistrent pas.
--

![lorsque on change les objectifs et qu'on actualise, les objetifs par default sont remis](https://user-images.githubusercontent.com/77858297/109865910-a7c75680-7c32-11eb-9ff2-30bb32dd6cd8.JPG)

**Comment by apajon** [comment]
J'ai testé.

L'objectif personnel est mis à jour avec les recommandations du clinicien lorsque celui-ci **clic** sur **sauvegarde**.
L'utilisateur doit alors changer sur son compte pour réajuster/remettre son objectif personnel.

Est-ce voulu ? peut-être. Il faut demander à Claudine.

J'imagine que si le clinicien met une nouvelle recommandation, il veut qu'elle soit suivi (en tout cas au début).
Puis si ça ne convient pas à l'utilisateur, il la réajuste avec le temps.
J'imagine que ça a été pensé comme ça avec l'utilisateur qui met plus souvent à jour son objectif avec le temps que le clinicien (genre 1 fois tous les x mois si faut changer la recommandation).

**Comment by Marie-LaurenceB** [comment]
Le problème est aussi que lorsque l'usager remet un autre objectif personnel après que le clinicien lui ait fait une recommandation, celui-ci ne se sauvegarde pas lorsqu'on actualise la page ou quon change d'onglet.

**Comment by apajon** [comment]
C'est bizarre, il faut que tu me montre ça car je ne voit pas ton problème. 
On a peut-être pas la même version du site.

**Comment by apajon** [comment]
@doumdi on a testé et je n'arrive à reproduire le bug de Marie-Laurence sur ma plateforme.

Pourtant, on a la même version du backend et du frontend ...
