### ISSUE TITLE
Changer motion unit

### ISSUE THREAD

**Issue by apajon** [introlab/MOvITPlus#30]
Le motion unit intial de la palteforme n'est pas satisfaisant.

Il nécessite un cable court pour que suffisamment d'énergie lui soit envoyé. Ce qui limite les possibilités pour le positionner.
Il se déconnecte assez souvent sans raison apparentes (ex : sans que rien ne bouge).
On n'est pas sûre qu'il détect bien les mouvement dans le meilleur des cas.

-> il faut le changer par un nouveau capteur ou une nouvelle méthode d'analyse des données que l'on peut déjà avoir.

**Comment by apajon** [comment]
@doumdi  J'ai créé une branche "test_new_motion_detection" dans movit-Detect
 
J'y ai push une première version du code de détection du mouvement à partir des vibrations de l'IMU fixe.
 
C'est @Marie-LaurenceB  qui a la plateforme avec les capteurs, du coup je n'ai pas encore testé si ça fonctionne.

**Comment by apajon** [comment]
On vient de tester, ça fonctionne sur la plateforme.
Il faut maintenant tester en live sur un FRM.
 
Il faudra peut-être jouer un peu avec les seuil de détection mais rien de bien méchant.

Pour finir, il va falloir retravailler un peu ``Travel.py`` et ``TravelFSM.py`` car il va falloir les optimiser et supprimer les parties inutiles (TravelX, TravelY, lastDistance, ...) qui n'ont plus lieux d'être

**Comment by doumdi** [comment]
@apajon , je laisserais tout de même le travelX, travelY, lastDistance pour éventuellement les capteurs qui pourraient donner ces valeurs.

**Comment by doumdi** [comment]
Dans le cas de la vibration on a juste à mettre TravelX et TravelY et lastDistance à un chiffre "réaliste".

**Comment by apajon** [comment]
Pour le moment `TravelX` et `TravelY` restent à 0.
`LastDistance` `= 0` si pas de vibration détectée, `= 101` si vibration détectée.
Mais j'ai fais ça simplement pour tester la validité avec `TravelFSM.py` et ne pas interférer avec NODE-RED.

Je peux les laisser pour plus tard. c'est juste que dans `TravelFSM.py` il se base sur `LastDistance` et son `cumsum` pour détecter s'il y a effectivement un mouvement en fonction de :
```python
TRAVEL_START_TIMEOUT = 1
TRAVEL_STOP_TIMEOUT = 2
TRAVEL_THRESHOLD = 100
```
Ça serait à retravailler car moi pour le moment je ne return qu'un `Bool` qui indique s'il y a des vibrations ou non (en fonction de seuils choisis)
Quand je ferais ça, je pense que je mettrais aussi ces attribut dans le `config.cfg`.

**Comment by apajon** [comment]
Je suis aussi en train de réorganiser le `config.cfg` avec des section pour chacun des codes que j'ai modifié jusqu'à maintenant et ceux que je modifierai dans le futur.

**Comment by doumdi** [comment]
Je crois qu'on devrait implémenter des unit tests pour tester les changements.

**Comment by Marie-LaurenceB** [comment]
J'ai testé en laboratoire vendredi et le code et les seuils fonctionne bien. Il faudrait valider avec d'autres tests complet.
