### ISSUE TITLE
Problème de résolution du site web sur téléphone portable

### ISSUE THREAD

**Issue by Marie-LaurenceB** [introlab/MOvITPlus#44]
La partie résultat n'est pas afficher quand on ouvre le site sur un téléphone. Doit y accéder directement par l'url du site. Les graphiques ne sont pas bien affiché en mode portrait du téléphone.

**Comment by doumdi** [comment]
https://github.com/introlab/MOvIT-Detect-Frontend/blob/0766d3b10f6fb89650bf6fc4147a7163a5a8caaa/src/views/header.js#L110

**Comment by doumdi** [comment]
https://github.com/introlab/MOvIT-Detect-Frontend/blob/0766d3b10f6fb89650bf6fc4147a7163a5a8caaa/src/redux/applicationReducer.js#L28
