### ISSUE TITLE
No space left on device raspberry

### ISSUE THREAD

**Issue by Marie-LaurenceB** [introlab/MOvITPlus#50]
Après que le Raspberry ait été allumé pendant longtemps sans interruption (environ une semaine), il ne fonctionne plus correctement à cause qu'il n'y a pu de place. La mémoire est full et on ne sait pas d'où provient cette accumulation de données. La base de données \dump à été supprimée. 

![image](https://user-images.githubusercontent.com/77858297/135668533-f410facc-e3e5-4b5c-806c-87c95c7f5f1b.png)

**Comment by doumdi** [comment]
@Marie-LaurenceB après le dump ça fonctionne ?

**Comment by Marie-LaurenceB** [comment]
Non toujours la même erreur.
