### ISSUE TITLE
low power message - try new power bank

### ISSUE THREAD

**Issue by apajon** [introlab/MOvITPlus#8]

**Comment by apajon** [comment]
initial ethernet cable is 20cm long.

maybe too long cable, there will be not enough power to supply the motion unit ?

**Comment by doumdi** [comment]
@apajon, SPI bus is not meant to be that long. That is why we used a 20 cm cable. Can you try with a smaller cable?

**Comment by apajon** [comment]
We were limited by the space on the PWC with 20cm and its rigidity.

At the time of the tests we had no other ethernet cable to use but this long one.
we bought a new one a little longer than 20cm. We will try it the next time.

**Comment by apajon** [comment]
We tried a 90cm cable and it work better than the very long one.

However, when the raspberry is on battery, the connexion with the motion unit is very unstable.
I mean, randomly, the motion unit is disconnected and reconnected.
It appears that moving the plug, connect/disconnect.
But it happens also when there is no movement.
We also get the message on the raspberry "low power, verify the power connection".
This happen with the 90cm and the 20cm cable

Plugging the adapter into a wall socket, is better but still unstable. It seems to deconnect with a lower frequency with the 90cm and is stable with the 20cm.
But due to the wall connection, we cannot move the seat ;)

**Comment by doumdi** [comment]
@apajon, I suspect the RPi4 is taking too much current from the regulator on the battery. They were chosen for the Pi Zero. Can you give me the exact model of the battery? For the motion unit, mine too is unstable. I think we might want to find another sensor that is less fragile. Any idea?

**Comment by doumdi** [comment]
@apajon,we should maybe [try this power bank](https://www.amazon.ca/26800mAh-External-Battery-Portable-Compatible/dp/B07RBSXSZ8/ref=sr_1_2_sspa?dchild=1&gclid=CjwKCAiAjp6BBhAIEiwAkO9Wusq16AFDspIUTqBIWiL7JyR69lrhNqusJV1SGYXOoF5DZcEDEYWM9RoCf-0QAvD_BwE&hvadid=320772440785&hvdev=c&hvlocphy=1002632&hvnetw=g&hvqmt=e&hvrand=8434115319341319799&hvtargid=kwd-301857305402&hydadcr=27679_10600075&keywords=5v+3a+power+bank&qid=1613217954&sr=8-2-spons&tag=googcana-20&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEzTVlCMTRKWUFIRjhGJmVuY3J5cHRlZElkPUEwMTY2ODE5MVVWVkczWTcwMDM2VCZlbmNyeXB0ZWRBZElkPUEwNDMzNDg1MVFZRVdVQjlXSzRCNiZ3aWRnZXROYW1lPXNwX2F0ZiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=)?

**Comment by apajon** [comment]
I renamed this issue as "low power message - try new power bank"

**Comment by apajon** [comment]
I will also create a new issue to change the motion unit with a different method/sensor to detect if there is a motion of the wheelchair.

**Comment by apajon** [comment]
> @apajon,we should maybe [try this power bank](https://www.amazon.ca/26800mAh-External-Battery-Portable-Compatible/dp/B07RBSXSZ8/ref=sr_1_2_sspa?dchild=1&gclid=CjwKCAiAjp6BBhAIEiwAkO9Wusq16AFDspIUTqBIWiL7JyR69lrhNqusJV1SGYXOoF5DZcEDEYWM9RoCf-0QAvD_BwE&hvadid=320772440785&hvdev=c&hvlocphy=1002632&hvnetw=g&hvqmt=e&hvrand=8434115319341319799&hvtargid=kwd-301857305402&hydadcr=27679_10600075&keywords=5v+3a+power+bank&qid=1613217954&sr=8-2-spons&tag=googcana-20&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEzTVlCMTRKWUFIRjhGJmVuY3J5cHRlZElkPUEwMTY2ODE5MVVWVkczWTcwMDM2VCZlbmNyeXB0ZWRBZElkPUEwNDMzNDg1MVFZRVdVQjlXSzRCNiZ3aWRnZXROYW1lPXNwX2F0ZiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=)?

@doumdi On a testé et on n'a plus le message "low Power", du coup je pense que l'on peut valider ce power bank
